"""add password to users, remove parent_id from cities

Revision ID: 0c8ae7c1c7e3
Revises: db4e71211b4e
Create Date: 2026-10-04 18:54:50.285758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8ae7c1c7e3'
down_revision: Union[str, Sequence[str], None] = 'db4e71211b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cities_parent_id_fkey'), 'cities', type_='foreignkey')
    op.drop_column('cities', 'parent_id')
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('cities', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cities_parent_id_fkey'), 'cities', 'cities', ['parent_id'], ['id'])
    # ### end Alembic commands ###
