"""lab3 constraints and seed user

Revision ID: 8ccb1ffe880b
Revises: 0c8ae7c1c7e3
Create Date: 2026-10-04 20:48:14.227012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ccb1ffe880b'
down_revision: Union[str, Sequence[str], None] = '0c8ae7c1c7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###

    op.create_check_constraint(
        "ck_cities_status", "cities",
        "status IN ('draft', 'published', 'deleted')",
    )
    op.create_unique_constraint("uq_likes_user_city", "likes", ["user_id", "city_id"])

    # пользователь-singleton с id=1
    op.execute(
        "INSERT INTO users (id, username) VALUES (1, 'demo_user') "
        "ON CONFLICT (id) DO NOTHING"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('users', 'id'), "
        "(SELECT MAX(id) FROM users))"
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_likes_user_city', 'likes', type_='unique')
    # ### end Alembic commands ###
