"""add parent_id to cities

Revision ID: db4e71211b4e
Revises: 987e2312b40b
Create Date: 2026-09-21 21:17:10.587237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4e71211b4e'
down_revision: Union[str, Sequence[str], None] = '987e2312b40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_foreign_key(None, 'cities', 'cities', ['parent_id'], ['id'])
    op.create_index(op.f('ix_likes_id'), 'likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_id'), table_name='likes')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_column('cities', 'parent_id')
    # ### end Alembic commands ###
